### ISSUE TITLE
continuously recording

### ISSUE THREAD

**Issue by christophe195** [magorbalassy/stream-recorder#5]
It would be useful if the program could record continuously and create files of an hour or so. if there is something useful you can do something with it and otherwise it can be deleted after a certain window

**Comment by magorbalassy** [comment]
Hi @christophe195, thx for opening this issue, sorry for the late reply... 
I've been recording 40 minute videos, and I would assume it'd work for longer videos as well, so recording one hour should not be a problem...did you experience any issue when setting video length of 60+ minutes ? I can only imagine as a potential issue that the file exceeds the maximum size allowed by the underlying filesystem...

**Comment by magorbalassy** [comment]
closing the issue, please reopen if needed
